# Generated by Django 5.0.7 on 2024-07-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("depth", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("barcode", models.CharField(max_length=255)),
                ("qr_code", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("date", models.DateTimeField()),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_percentage", models.FloatField()),
                ("rating", models.FloatField()),
                ("stock", models.IntegerField()),
                ("tags", models.JSONField()),
                ("brand", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=255)),
                ("weight", models.FloatField()),
                ("warranty_information", models.CharField(max_length=255)),
                ("shipping_information", models.CharField(max_length=255)),
                ("availability_status", models.CharField(max_length=255)),
                ("return_policy", models.CharField(max_length=255)),
                ("minimum_order_quantity", models.IntegerField()),
                ("images", models.JSONField()),
                ("thumbnail", models.URLField()),
                (
                    "dimensions",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dimension"
                    ),
                ),
                (
                    "meta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.meta"
                    ),
                ),
                ("reviews", models.ManyToManyField(to="api.review")),
            ],
        ),
    ]
