# Generated by Django 5.0.7 on 2024-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
